language: node_js
sudo: false

addons:
  chrome: stable

node_js:
  - "8"

env:
  - BROWSER=true

cache:
  directories:
  - node_modules

dist: xenial

services:
  - xvfb

install:
  - npm install -g yarn
  - yarn

script:
  # - npm run lint
  - BROWSER=true COVERAGE=true FLAKEY=false npm run test:karma
  - npm run build:site
  - npm run build:component
  # - npm run test:coverage
  - ./node_modules/coveralls/bin/coveralls.js < ./coverage/lcov.info

after_script:
  - cd siteoutput
  - git init
  - git add .
  - git commit -m "Update Document"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages


branches:
  only:
    - master
  